### PR TITLE
add credentials: same-origin

### PR DESCRIPTION
**Pull request by rapto**
It seems reasonable to allow same-origin authentication. If this is not the case, I could rewrite this as an option.

### CODE REVIEW

**Comment by jonataswalker** [comment]
@walkermatt Could you review this PR please?

**Comment by walkermatt** [comment]
I think setting the fetch init object `credentials` value to `same-origin` is fine. As explained in the [MDN fetch docs](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Sending_a_request_with_credentials_included) `same-origin` will result in credentials being sent only if the request URL is on the same origin as the calling script.

@rapto I assume you're using this with a custom provider which sends requests to the same origin?

**Comment by walkermatt** [comment]
If you can commit just the single change to `src/helpers/ajax.js` and not the other changes I'd be happy to merge.

**Comment by rapto** [comment]
Yes, they are different applications at our server. I'll prepare a proper pull request.

**Comment by jonataswalker** [comment]
Merged #155

**Pull request closed without merging**
