### PR TITLE
Changed Nominatim related URLs to https

### PR DESCRIPTION
**Pull request by cyrix2000**
Wouldn't it make sense to use https wherever possible? I had problems using the ol-geocoder library on my webserver, as browsers will complain about a mix of http and https connections.

### CODE REVIEW

**Comment by jonataswalker** [comment]
Which specific provider are you talking about?

**Comment by cyrix2000** [comment]
These two:
"https://nominatim.openstreetmap.org/search/"
"https://open.mapquestapi.com/nominatim/v1/search.php"

They were as http in the original file.

**Comment by jonataswalker** [comment]
OSM is [already `https`](https://github.com/jonataswalker/ol-geocoder/blob/54b23aea313d484e315e89d246232979565cce30/src/providers/osm.js#L11) by default and [Mapquest doesn't offer](https://developer.mapquest.com/documentation/open/nominatim-search/search/) `https`.

**Comment by jonataswalker** [comment]
And to your PR get merged you should edit source files not the final bundle.

**Pull request closed without merging**
