### PR TITLE
Add support for providers returning a bbox for each result

### PR DESCRIPTION
**Pull request by walkermatt**
By default if a bbox is returned use ol.View#fit to zoom to the extent.

Requires OpenLayers > v4.0.0

### CODE REVIEW

**Comment by walkermatt** [comment]
@jonataswalker this requires OpenLayers > v4.0.0 for `ol.View#fit` are you OK with bumping to v4?

**Comment by jonataswalker** [comment]
@walkermatt Yeah, we'll release a major version. Thank you.

**Comment by walkermatt** [comment]
@jonataswalker any idea why the build might of broken following this change?

See: https://travis-ci.org/jonataswalker/ol-geocoder/builds/300060214

**Comment by jonataswalker** [comment]
@walkermatt I rewrote a bunch of files, see #134.

**Pull request merged**
